export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE'
export const START_FETCHING_USER_GISTS = 'START_FETCHING_USER_GISTS'
export const DONE_FETCHING_USER_GISTS = 'DONE_FETCHING_USER_GISTS'
export const SET_USER_GISTS_PAGINATION = 'SET_USER_GISTS_PAGINATION'
export const SET_USER_GISTS_PAGE = 'SET_USER_GISTS_PAGE'